import { DesignToken, InstitutionType } from "../types";

// Expanded from the prior project's 6-palette design-system.ts (C:\claude_cowork\ppt\...\app\design-system.ts),
// tagged so the engine can match on institution type, industry keywords, and audience together.
// Korean font: default to 맑은 고딕 everywhere — it's reliably present on Korean Windows/PowerPoint,
// so headings stay bold-weight of the same face instead of risking tofu from an uninstalled display font.

export interface DesignPreset extends DesignToken {
  institutionTypes: InstitutionType[];
  keywords: string[];
}

export const DESIGN_PRESETS: DesignPreset[] = [
  {
    id: "public_data",
    label: "Public Data Blue",
    background: "F5F7F6",
    surface: "DDEDEA",
    textPrimary: "102A2D",
    textSecondary: "607275",
    primary: "087E78",
    accent: ["B7DE31"],
    fontHeading: "맑은 고딕",
    fontBody: "맑은 고딕",
    mood: ["신뢰", "정책", "정보위계"],
    shapeLanguage: "sharp",
    institutionTypes: ["public_general", "school"],
    keywords: ["공공", "공기업", "재단", "공단", "정부", "지자체", "센터"],
  },
  {
    id: "public_bid_formal",
    label: "Formal Navy Report",
    background: "FFFFFF",
    surface: "E7ECF5",
    textPrimary: "13203A",
    textSecondary: "5A6478",
    primary: "1B3A6B",
    accent: ["C0392B"],
    fontHeading: "맑은 고딕",
    fontBody: "맑은 고딕",
    mood: ["formal", "보고서", "심사"],
    shapeLanguage: "sharp",
    institutionTypes: ["public_bid"],
    keywords: ["입찰", "제안요청서", "RFP", "나라장터", "평가"],
  },
  {
    id: "corporate_strategy",
    label: "Corporate Strategy",
    background: "F4F1EA",
    surface: "DCE6F8",
    textPrimary: "14181D",
    textSecondary: "697078",
    primary: "1755D1",
    accent: ["FF5A36"],
    fontHeading: "맑은 고딕",
    fontBody: "맑은 고딕",
    mood: ["실무", "임원보고", "데이터"],
    shapeLanguage: "sharp",
    institutionTypes: ["corporate"],
    keywords: ["기업", "임직원", "업무효율", "사내"],
  },
  {
    id: "tech_neon",
    label: "Tech Neon Grid",
    background: "0B1020",
    surface: "192747",
    textPrimary: "F5F7FF",
    textSecondary: "A9B5CF",
    primary: "7857FF",
    accent: ["31E6C5"],
    fontHeading: "맑은 고딕",
    fontBody: "맑은 고딕",
    mood: ["테크", "미래지향", "다크모드"],
    shapeLanguage: "sharp",
    institutionTypes: ["corporate", "event"],
    keywords: ["개발", "IT", "AI", "인공지능", "데이터", "테크", "스타트업"],
  },
  {
    id: "youth_pop",
    label: "Youth Pop Lab",
    background: "F7F5FF",
    surface: "E8E0FF",
    textPrimary: "171527",
    textSecondary: "666078",
    primary: "6746E8",
    accent: ["B8F13C"],
    fontHeading: "맑은 고딕",
    fontBody: "맑은 고딕",
    mood: ["청년", "활기", "창업"],
    shapeLanguage: "rounded",
    institutionTypes: ["school", "event"],
    keywords: ["청년", "20대", "대학생", "창업"],
  },
  {
    id: "school_fresh",
    label: "School Fresh Green",
    background: "F6FAF2",
    surface: "E1F0D4",
    textPrimary: "1F3319",
    textSecondary: "5C6E54",
    primary: "3E8E3E",
    accent: ["F2A93B"],
    fontHeading: "맑은 고딕",
    fontBody: "맑은 고딕",
    mood: ["학교", "성장", "친근"],
    shapeLanguage: "rounded",
    institutionTypes: ["school"],
    keywords: ["학생", "학년", "교사", "학교", "대학", "진로"],
  },
  {
    id: "small_business_bright",
    label: "Small Business Bright",
    background: "FFFBF2",
    surface: "FCE9C9",
    textPrimary: "402E12",
    textSecondary: "7A6438",
    primary: "E08A1E",
    accent: ["2E7D6B"],
    fontHeading: "맑은 고딕",
    fontBody: "맑은 고딕",
    mood: ["현장감", "쉬움", "실용"],
    shapeLanguage: "rounded",
    institutionTypes: ["small_business"],
    keywords: ["소상공인", "자영업자", "점포", "매장", "상권"],
  },
  {
    id: "warm_lifestyle",
    label: "Warm Lifestyle",
    background: "FFF8EF",
    surface: "F7DED6",
    textPrimary: "4B342E",
    textSecondary: "806B64",
    primary: "D9666F",
    accent: ["F0B84B"],
    fontHeading: "맑은 고딕",
    fontBody: "맑은 고딕",
    mood: ["따뜻함", "돌봄", "여유"],
    shapeLanguage: "rounded",
    institutionTypes: ["public_general", "small_business"],
    keywords: ["엄마", "부모", "시니어", "노인", "복지", "육아", "가족"],
  },
  {
    id: "event_energetic",
    label: "Event Energetic",
    background: "FFF4F0",
    surface: "FFD9CC",
    textPrimary: "301A12",
    textSecondary: "7A5546",
    primary: "E8492E",
    accent: ["1B3A6B"],
    fontHeading: "맑은 고딕",
    fontBody: "맑은 고딕",
    mood: ["에너지", "모객", "행사"],
    shapeLanguage: "rounded",
    institutionTypes: ["event"],
    keywords: ["행사", "특강", "세미나", "설명회", "모집", "접수"],
  },
  {
    id: "premium_editorial",
    label: "Premium Editorial",
    background: "F2EFE8",
    surface: "DED8CD",
    textPrimary: "111111",
    textSecondary: "6B6964",
    primary: "C8482E",
    accent: ["E8C96A"],
    fontHeading: "맑은 고딕",
    fontBody: "맑은 고딕",
    mood: ["브랜드", "리더십", "프리미엄"],
    shapeLanguage: "sharp",
    institutionTypes: ["corporate", "public_general"],
    keywords: ["브랜드", "리더", "임원", "프리미엄", "문화", "예술"],
  },
];

export function getPresetById(id: string): DesignPreset | undefined {
  return DESIGN_PRESETS.find((p) => p.id === id);
}
